name: Demo

on:
  pull_request:

jobs:
  build:
    name: Build test image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:demo-container-paths

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}:demo-container-paths
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Pyright
        uses: codequest-eu/pyright-action@feat/workspace-input
        with:
          version: PATH
          workspace-directory: /opt/demo
